{% set name = "chainer" %}
{% set version = "7.8.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/chainer-{{ version }}.tar.gz
  sha256: 179f06176f8d7a42385bc7811956db04e68213cfe30f5081491b9e2b6ff70de8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - filelock
    - numpy >=1.9.0
    - protobuf >=3.0.0
    - python >=3.5
    - setuptools
    - six >=1.9.0
    - typing_extensions

test:
  imports:
    - chainer
    - chainer.backends
  commands:
    - pip check
  requires:
    - pip
about:
  home: https://chainer.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A flexible framework of neural networks
  doc_url: https://docs.chainer.org/en/stable/
  dev_url: https://pypi.org/project/chainer/

extra:
  recipe-maintainers:
    - mxr-conda
