travis:
  secure:
    BINSTAR_TOKEN: FMEXpMg/Vl96Xy5nHONC7tPd5YFxz/6gMz/c/kzZjA+w/GUoQtTGlLqDzWzCCNO2n8iSmnAhZt2qEDY7iJz5/qqozvgduuLxFxsfmSi5j6qtBx8SHoEbdNOWwb9lpk6naRgdY9jCNyaaMtsEpgzuKjGAR40rl9CMdCrwciK5xOb7G3iE1cmGhNz5dG8om2hbzsAA3QbvxUDODhG/Cl5ACYYshErN5YGAU4FUz+Ma+3MS0ONYwwiDOLrcUWe6boutaNOC70ZgpdSc9txbcMKYWaX3jmWK9UNfhgteeyxxe6m+ATVP6pwT0dLI1Dr/1LUmtyWN8VzZpTg+ESBYDdlZvwoeU2DJ0WR4RXWlEC96DddS4Mp2Kl0QVahbCXLAfRdAAdEvOtkc7DGWf9p9dNObzdiK/6K3NfkuKcbedrEDu5OR8cOBNKuPfWbfJoLW30SDMgid9y/NTvS/xDhkLf1fDO5ALnqznJSKr0xqHC6Y6vV2/F4ZfNxl5zAZGPEMP/58SZJYNUgbnA7uJxkIOAjz6kiey3OhJB+ASNprv/fgP9yy71Y5QIoyEz8fbkSGku05Ge0DiG3w39jIPEGShZbpJgfhvtTrC2K+BG7njyYg4sqXnS0hER6btLO/0F4JUYEGIKoyovz54QYrqmAMKKuy5CD6Ac33h7h6DDmKq/keQKs=
conda_forge_output_validation: true
bot:
  automerge: true
github:
  branch_name: main
  tooling_branch_name: main
